main: com.alw3ys.sinusforminecraft.SinusForMinecraftPlugin
name: ${project.name}
description: ${project.description}
version: ${project.version}
author: Alw3ys

commands:
  ttb:
    description: Toggle track broadcasts
  track:
    description: Current playing track information